var type_texts = [
    "A penny saved is a penny earned.",
    "Never look back. They might be gaining on you.",
    "A stitch in time saves nine.",
    "The only thing you have to fear is fear itself.",
    "The rate at which inflation is increasing is decreasing.",
    "However, the rate at which the increase of inflation is decreasing is increasing.",
    "Rubber baby buggy bumpers.",
    "All bubble blowing babies will be beaten senseless by every able-bodied patron in the bar (bar).",
    "Every positive adjective was severely modified, if not completely contradicted by, an accompanying adverb.",
    "Road work ahead? Uh, yeah. I sure hope it does!",
    "East? I thought you said, \" Weast.\"",
    "One must never contradict an active love",
    "Are you calling me a liar? I ain't calling ya for dinner.",
    "Hope you're happy.",
    "Ride with the mob.",
    "Howdy.",
    "Pleased to meet you.",
    "Hello?",
    "Greetings.",
    "Salutations.",
    "Hello.",
    "Hi!",
    "Hey",
    "Ferg is the name. Ben Baller did the chain.",
    "Today we have a Jelly Belly Pet Rat Gummi Candy.",
    "Affirmative",
    "Nobody knows, the troubles I've seen",
    "Nobody knows, my sorrow.",
    "5 plus 5 equals 10.",
    "e4 is best by test.",
    "This is a test of the intercom system.",
    "Indeed.",
    "How much wood could a woodchuck chuck if a woodchuck could chuck wood?",
    "Quite indeed, considering the efficacy of Fermat's Little Theorem.",
    "I encompass, and I eclipse. Ooh, got the hiccups.",
    "Shawty come again; tell me what your mood 'bout; maybe we can move out; go to where it's nice out",
    "Couldn't agree more, Stanley.",
    "Why am I typing this?",
    "I am doing this instead of my Ph.D. thesis",
    "Ruby on Rails",
    "Typing these all out was very fun.",
    "A man, a plan, a canal. Panama.",
    "Yea verily.",
    "I been on the moon",
    "She said I'm the man because I bought her Louboutins",
    "1.e4 e5 2.Ke2!!",
    "$we love jQuery :)",
    "A module is Noetherian if and only if all of its submodules are finitely generated.",
    "1.e4 e5 2.Nf3?? Ke7!!",
    "Now I will do what others won't, so tomorrow I can do what others can't.",
    "\"Cuius rei demonstrationem mirabilem sane detexi hanc marginis exiguitas non caperet.\" - Pierre de Fermat",
    "Not much of a math game really is it",
    "Koejawel.",
    "Kweper.",
    "The cycle of life and death continues: we will live; they will die.",
    "The Bolzano-Weierstrass Theorem states that every bounded sequence in R^n has a convergent subsequence.",
    "There exists a topology in which the real line is compact.",
    "The rational numbers are a DENSE subset of the real numbers.",
    "She said I'm the man because I look like Pierre Fermat",
    "I came. I saw. I came. I saw. I praise - the lord. And break - the law.",
    "YoooOOOOOoOOoOoooOooO",
    "I really should've made a lorem ipsum dump instead of writing all these myself",
    "Gordon Palmer",
    "I love math!",
    "I'm thinking \"Loedewiekie Koekie\" is a viable option.",
    "Squidward will be performing his version of Solitude in E Minor.",
    "Yeah! E Minor, alright, yeah!",
    "Spongebob! We're not cavemen -- we have technology.",
    "Some - T-rex, bohnth, in my yard; can you believe that?",
    "And so -- of course -- I had to ... clarefully take out this precious bone",
    "Ok, times up!",
    "And I dust it off. A ha ha ha",
    "That angle",
    "Walk out the crib with an ice cream sandwich.",
    "Javaris Jamar Javarison-Lamar!",
    "Davoin Shower-Handel",
    "Jackmerius Tacktheritrix",
    "Rome wasn't built in a day.",
    "Listen. My motto is no beef: literal, or figurative.",
    "I woke up in a new Bugatti",
    "V A P O R W A V E",
    "I want a brand new whip. I want a brand new house.",
    "I fell in love - same time that you're falling apart",
    "I shoulda known - thought I saw a sign in the stars",
    "But I was wrong!",
    "I used to be so devastated - at times I thought we'd never make it",
    "My Ryze is bad. My Azir is worse. You guessed it right; I'm G2 Perkz.",
    "Since LA, I been putting on",
    "Cirque de Soleil, on and on and on",
    "144 is a perfect square.",
    "145 is not a perfect square.",
    "Putting economic policy before fiscal responsibility is like putting the cart before the horse.",
    "Venmo me your lunch money, nerd.",
    "Need to get the lambo and drive",
    "I was in the lab; you were on my mind. But all I really do is just grind",
    "Who'd do the stuff that I do??",
    "I coulda went (sic) to school to be a doctor. But I dropped out and chose to be a baller.",
    "Cash in the area; what goes up, gotta come down.",
    "I'm so glad that you came",
    "I'm trapped in my conscious",
    "Where's the love if you love me?",
    "The sky keep on falling",
    "I don't wanna buy no more",
    "Ima die rich. Keep a side chick. That's just how it is - just in case you didn't know",
    "Represent the men who get reckless for that yen",
    "I'll never let you let me go",
    "Yo Pierre, you wanna come out here?",
    "In New York I Milly Rock",
    "Baking soda! I got baking soda!",
    "We dem boyz",
    "I got loyalty, got royalty inside my DNA",
    "I got millions, I got riches building in my DNA",
    "Every time I'm in the street, I hear, \"Yok Yok Yok Yok\".",
    "Yeah, something inside me's changed - I was so much younger yesterday",
    "Swish! I'm balling. I'm so awesome.",
    "They said I wouldn't be nothing; now they always say, \"Congratulations!\"",
    "Oh, I want something just like this!",
    "I was about to text you back... but then I hopped up in the drop",
    "Walking with a check, I take lil' shawty out for lunch",
    "Walk. We don't no talking. Got your man calling. I need better options.",
    "I came, I saw. I conquered all.",
    "Pull up, shoot! Jayson Tatum",
    "I went on a date with this girl, and her floor was just bean bags.",
    "Soulja boy up in it; watch me crank it, watch me; watch me crank that soulja boy",
    "\"I dunno. CAN you go to the bathroom? Can you?\" - My middle school teacher, Mrs. Trisket",
    "\"57 is prime.\" - Grothendieck",
    "\"There are no prime numbers except for 57.\" - Grothendieck",
    "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela",
    "\"The way to get started is to quit talking and begin doing.\" - Walt Disney",
    "\"If life were predictable it would cease to be life, and be without flavor.\" - Eleanor Roosevelt",
    "\"It is during our darkest moments that we must focus to see the light.\" - Aristotle",
    "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
    "\"Whether you think you can or you think you can't, you're right.\" - Henry Ford",
    "\"Dream big and dare to fail.\" - Norman Vaughan",
    "\"I didn't fail the test. I just found 100 ways to do it wrong.\" - Benjamin Franklin",
    "\"Imagine if I had a real weapon.\" - Jax",
    "\"I would rather die of passion than of boredom.\" - Vincent van Gogh",
    "\"Dreaming, after all, is a form of planning.\" - Gloria Steinem",
    "\"I have no special talent. I am only passionately curious.\" - Albert Einstein",
    "\"Wisely, and slow. They stumble that run fast.\" - William Shakespeare",
]