var type_texts = [
    "A penny saved is a penny earned.",
    "Never look back. They might be gaining on you.",
    "A stitch in time saves nine.",
    "The only thing you have to fear is fear itself.",
    "The rate at which inflation is increasing is decreasing.",
    "Rubber baby buggy bumpers.",
    "Road work ahead? Uh, yeah. I sure hope it does..",
    "East? I thought you said, \" Weast.\"",
    "One must never contradict an active love",
    "Ferg is the name. Ben Baller did the chain.",
    "Today we have a Jelly Belly Pet Rat Gummi Candy.",
    "Nobody knows, the troubles I've seen",
    "Nobody knows, my sorrow.",
    "e4 is best by test.",
    "This is a test of the intercom system.",
    "Couldn't agree more, Stanley.",
    "Typing these all out was very fun.",
    "A man, a plan, a canal. Panama.",
    "Not much of a math game really is it",
    "Yeah! E Minor, alright, yeah!",
    "And I dust it off. A ha ha ha",
    "Walk out the crib with an ice cream sandwich.",
    "Javaris Jamar Javarison-Lamar!",
    "Davoin Shower-Handel",
    "Jackmerius Tacktheritrix",
    "Rome wasn't built in a day.",
    "I woke up in a new Bugatti",
    "But I was wrong!",
    "Since LA, I been putting on",
    "Cirque de Soleil, on and on and on",
    "Venmo me your lunch money, nerd.",
    "Need to get the lambo and drive",
    "Who'd do the stuff that I do??",
    "I'm so glad that you came",
    "I'm trapped in my conscious",
    "Where's the love if you love me?",
    "The sky keep on falling",
    "I don't wanna buy no more",
    "I'll never let you let me go",
    "Yo Pierre, you wanna come out here?",
    "In New York I Milly Rock",
    "Baking soda! I got baking soda!",
    "I got loyalty, got royalty inside my DNA",
    "I got millions, I got riches building in my DNA",
    "Swish! I'm balling. I'm so awesome.",
    "Oh, I want something just like this!",
    "I came; I saw. I conquered all.",
    "Pull up, shoot! Jayson Tatum",
    "I dunno. CAN you go to the bathroom? Can you?",
    "\"57 is prime.\" - Grothendieck",
    "\"Imagine if I had a real weapon.\" - Jax",
    "I cahn't believe you've done this.",
    "The proof is trivial.",
    "We talkin about PRACTICE. Not a game.",
    "And they were roommates!",
    "Oh my god they were roommates",
    "Nah they usually tell me I look like Shalissa",
    "I'm just chillin' in Cedar Rapids",
    "Ha ha ha. I do that.",
    "Permission denied. You have been stopped.",
    "What is love? Baby don't hurt me",
    "We accept the love we think we deserve.",
    "Only once in your life, I truly believe...",
    "Love all, trust a few, do wrong to none.",
    "Cause you make my earf quake!",
    "All Euclidean Domains are Principal Ideal Domains.",
    "Lorem ipsum dolor sit amet.",
    "My name is Ozymandias, King of Kings.",
    "Look on my Works, ye Mighty, and despair!",
    "Do not go gentle into that good night.",
    "Rage, rage, against the dying of the light.",
    "Red Robin: yum.",
    "I got standards: diamonds Ned Flanders.",
    "I don't want a valentine; I just want valentino",
    "Through the fire and the flames we'll carry on.",
    "I ain't got no friends; I'm too focused on the bands.",
    "Standing in the Hall of Fame!",
    "Exit, light! Enter, night!",
    "Take me back to the night we met",
    "Break UP with your girlfriend... because I'm bored.",
    "Bevolo got that SAUCE.",
    "They like how we lit now; end up at a friend's house",
    "Yeah, meet me at the london",
    "It comes and goes in waves; it always does.",
    "Hol up, wait, ice skate",
    "We're a finite simple group of order 2",
    "Did I really just forget that melody?",
    "Hit or miss: I guess they never miss, huh.",
    "Here she comes: she's so perfect!",
    "Wise men say: only fools rush in...",
    "I been getting dirty money, Jordan Belfort",
    "Just dance; it'll be ok. Da da doo doo",
    "In a room feeling antisocial",
    "I'm a dog. I go ham; I'm a hog.",
    "I need some company. I NEED SOME COMPANY!",
    "Don't stop; make it pop; DJ blow my speakers up",
    "I'm a young CEO, Suge.",
    "In a sky full of stars, I think I see you!",
]

var long_texts = [
    "Putting economic policy before fiscal responsibility is like putting the cart before the horse.",
    "\"I would rather die of passion than of boredom.\" - Vincent van Gogh",
    "\"Dreaming, after all, is a form of planning.\" - Gloria Steinem",
    "\"I have no special talent. I am only passionately curious.\" - Albert Einstein",
    "\"Wisely, and slow. They stumble that run fast.\" - William Shakespeare",
    "\"There are no prime numbers except for 57.\" - Grothendieck",
    "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
    "I went on a date with this girl, and her floor was just bean bags.",
    "I was about to text you back... but then I hopped up in the drop",
    "Walking with a check, I take lil' shawty out for lunch",
    "Walk. We don't no talking. Got your man calling. I need better options.",
    "They said I wouldn't be nothing; now they always say, \"Congratulations!\"",
    "Every time I'm in the street, I hear, \"Yok Yok Yok Yok\".",
    "Yeah, something inside me's changed - I was so much younger yesterday",
    "Ima die rich. Keep a side chick. That's just how it is - just in case you didn't know",
    "Represent the men who get reckless for that yen",
    "Cash in the area; what goes up, gotta come down.",
    "I was in the lab; you were on my mind. But all I really do is just grind",
    "I used to be so devastated - at times I thought we'd never make it",
    "My Ryze is bad. My Azir is worse. You guessed it right; I'm G2 Perkz.",
    "I want a brand new whip. I want a brand new house.",
    "I fell in love - same time that you're falling apart",
    "I shoulda known - thought I saw a sign in the stars",
    "Listen. My motto is no beef: literal, or figurative.",
    "The cycle of life and death continues: we will live; they will die.",
    "There exists a topology in which the real line is compact.",
    "The rational numbers are a DENSE subset of the real numbers.",
    "She said I'm the man because I look like Pierre Fermat",
    "I'm thinking \"Loedewiekie Koekie\" is a viable option.",
    "Squidward will be performing his version of Solitude in E Minor.",
    "She said I'm the man because I bought her Louboutins",
    "Now I will do what others won't, so tomorrow I can do what others can't.",
    "However, the rate at which the increase of inflation is decreasing is ALSO decreasing.",
    "Quite indeed, considering the efficacy of Fermat's Little Theorem.",
    "Are you calling me a liar? I ain't calling ya for dinner.",
    "Some T-rex bones in my yard; can you believe that?",
    "I encompass, and I eclipse. Ooh, got the hiccups.",
    "Shawty come again; tell me what your mood 'bout",
    "\"Dream big and dare to fail.\" - Norman Vaughan",
    "The proof is trivial and is left as an exercise to the reader.",
    "What do you mean my intuition doesn't constitute a rigorous proof?",
    "Even though I'm closed under multiplication, girls don't see me as ideal.",
    "Oh! Blocked by James! LeBron James with the rejection!",
    "Why can't you grow corn in Z mod 6? Because it's not a field!",
    "Why can't you grow corn in Z mod 5? Because it's an abstract mathematical concept",
    "I heard Grothendieck tried growing corn in Z mod 57 once.",
    "And the Blazers win the series for the first time in 14 years!",
    "What's purple and commutes? An abelian grape!",
    "What's yellow and complete? A bananach space!",
    "\"Do unto others as you would want them uh onto to do onto others\" - Tai Lopez",
    "\"Basketball or ball-ske-bask or bathroom ball or TENNIS\" - Tai Lopez",
    "You can't sit with us. Actually Megan, I can't sit ANYWHERE.",
    "My name is Michael with a B, and I've been afraid of insects my whole life.",
    "I fell in love the way you fall asleep: slowly, and then all at once.",
    "A is average, B is bad, and C is catastrophic.",
    "What's green and has wheels? Grass. I lied about the wheels.",
    "Why didn't Newton discover group theory? He wasn't Abel!",
    "Why was 7 afraid of 8? Induction!",
    "A topologist playing poker: \"Man, I fold.\"",
    "You should really avoid building FSMs using LaTeX while hiking. Nobody likes Tikz.",
    "Once upon a midnight dreary, while I pondered, weak and weary...",
    "Give me one reason to stay here, and I'll turn right back around.",
    "The path of love is never smooth ... but mine's continuous for you",
    "I'm living in the kernel of a rank one map.",
    "I'm not the smoothest operator in my class, but we're a mirror pair.",
    "Trouble is a friend, yeah, trouble is a friend of mine",
    "You told me you loved me; why did you leave me (all alone)",
    "She was holding hands with Trevor, not the greatest feeling ever.",
    "What a wicked game you play. I've never felt this way.",
    "Do you ever think?? When you're all alone?? All that we could be?? Where this thing could go??",
    "Ok, excuse me: Mr. Bill Collector, I got problems.",
    "She ain't a stranger to the city life. I introduce her to this hippie life.",
    "Get away from me. If I was you, I'd watch what you say to me.",
    "You make some paper, then you make your own rules.",
    "Wait, if I'm on fire, how am I so deep in love?",
    ""
]